-- BustCard D1 Schema

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL UNIQUE,  -- mobile number, used as caller identifier
  dob_hash TEXT NOT NULL,      -- SHA-256 of DDMMYY — second factor
  active INTEGER DEFAULT 1,
  plan TEXT DEFAULT 'free',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contacts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  relationship TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id),
  triggered_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  contacts_notified INTEGER DEFAULT 0,
  caller_number TEXT,
  status TEXT DEFAULT 'sent'
);

CREATE TABLE IF NOT EXISTS deadman_switches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  fires_at DATETIME NOT NULL,
  location TEXT,
  message TEXT,
  cancel_token TEXT NOT NULL UNIQUE,
  cancelled INTEGER DEFAULT 0,
  fired INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS waitlist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  source TEXT DEFAULT 'landing',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
