name = "bustcard"
main = "src/worker.js"
compatibility_date = "2024-03-31"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "bustcard_db"
database_id = "009c6e3d-f338-4fa3-b3f3-a0688a181314"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "busted.theradicalparty.com/*"
zone_name = "theradicalparty.com"

[triggers]
crons = ["* * * * *"]
